### ISSUE TITLE
Missing header and truncated annotation table on GO:0004722 page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1849]
https://www.pombase.org/term/GO:0004722

I think the NOT annotation is causing problems because that's where the table is truncated.

![GO_0004722-bug-1](https://user-images.githubusercontent.com/90474/156963650-3a774df9-5e56-44cf-b4fe-a1cd5dbfd656.png)

![GO_0004722-bug-2](https://user-images.githubusercontent.com/90474/156963656-572a073d-137b-49df-ab41-73215fdd51fc.png)

Lots of console errors too:
```
core.mjs:6485 ERROR TypeError: Cannot read properties of undefined (reading 'uniquename')
    at GeneLinkComponent_a_3_Template (template.html:10:4)
    at executeTemplate (core.mjs:9618:1)
    at refreshView (core.mjs:9484:1)
    at refreshEmbeddedViews (core.mjs:10609:1)
```

**Comment by kimrutherford** [comment]
Fixed!  There was a serious bug and a minor bug.
