### ISSUE TITLE
Investigate internal error from gene expression plot code

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2034]
I noticed this in the pombase.org server logs.  I don't know the cause, but it needs fixing.

```
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    | IndexError: single positional indexer is out-of-bounds
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    | Internal Server Error: /gene_ex/gene_ex_violin/
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    | Traceback (most recent call last):
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 56, in inner
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |     response = get_response(request)
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 197, in _get_response
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |   File "/pombase/pombase-python-web/gene_ex/views.py", line 112, in gene_ex_violin
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |     sns.swarmplot(ax=ax, order=plot_order[idx], data=gene_frames[idx], size=swarm_dot_size, x='dataset_name', y="log_average_copies_per_cell", color="red")
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |   File "/usr/local/lib/python3.9/dist-packages/seaborn/categorical.py", line 2664, in swarmplot
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |     p.plot_swarms(
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |   File "/usr/local/lib/python3.9/dist-packages/seaborn/categorical.py", line 341, in plot_swarms
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |     for sub_vars, sub_data in self.iter_data(iter_vars,
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |   File "/usr/local/lib/python3.9/dist-packages/seaborn/_oldcore.py", line 1044, in iter_data
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |     converter = self.converters[axis].iloc[0]
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |   File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1073, in __getitem__
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |     return self._getitem_axis(maybe_callable, axis=axis)
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |   File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |     self._validate_integer(key, axis)
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |   File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 1557, in _validate_integer
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    |     raise IndexError("single positional indexer is out-of-bounds")
main-1.1.l354c0sq4tpy@pombase.babraham.ac.uk    | IndexError: single positional indexer is out-of-bounds
```

**Comment by kimrutherford** [comment]
The error occurred when viewing gene expression on gene pages when the gene either had no protein expression results or no RNA expression results (example: bqt2 / SPAC1002.06c).  It could also happen when viewing the violin plot for a list of gene when either none of the genes had protein expression results or none of the genes had RNA expression results.  For example: https://www.pombase.org/gene-ex/from/id/db348af2-f530-418c-845a-e58755e9caf4

I've fixed the problem and I'm about to update the main site with the fix.
